<div id="main-tab-content5" class="main-tab-content">
    <input type="radio" name="subtabs" id="subtab1"<?php if(!defined('LANGUAGE') || LANGUAGE=='DE'): ?> checked="checked"<?php endif; ?> />
    <label for="subtab1" class="subtab">
        DE
    </label>
    <input type="radio" name="subtabs" id="subtab2"<?php if(defined('LANGUAGE') && LANGUAGE=='EN'): ?> checked="checked"<?php endif; ?> />
    <label for="subtab2" class="subtab">
        EN
    </label>

    <div id="sub-tab-content1" class="sub-tab-content">
<?php include 'readme_de.txt'; ?>
    </div> <!-- 1 -->
    <div id="sub-tab-content2" class="sub-tab-content">
<?php include 'readme_en.txt'; ?>
    </div> <!-- 2 -->
</div>