<?php
    $add_article_button = '<form name="addarticle" action="'.$data['edit_url'].'" method="post" enctype="multipart/form-data">'.
                          '<input type="submit" class="btn btn-primary" name="mod_journal_add_article" value="' . self::t('Add article') . '" />'.
                          '</form>';
?>
        <div id="main-tab-content1" class="main-tab-content">
<?php if(count($data['articles'])>0): echo $add_article_button; ?>
            <div style="text-align:right;font-style:italic">
                <?php echo self::t('Order by'), ": <span class=\"\" title=\"", ( $settings['view_order']=='0' ? self::t('The setting &quot;custom&quot; allows the manual sorting of articles via up/down arrows.') : '') ,"\">", self::t($data['orders'][$settings['view_order']]['order_name']) ?></span>
            </div>
<?php endif; ?>
            <form name="modify_<?php echo $sectionID; ?>" action="<?php echo $data['edit_url'] ?>" method="post" enctype="multipart/form-data">
                <?php echo self::admin()->getFTAN(); ?>
                <input type="hidden" name="section_id" value="<?php echo $sectionID; ?>" />
                <input type="hidden" name="page_id" value="<?php echo $pageID; ?>" />
<?php if(count($data['articles'])>0): ?>
                <div class="scrollable">
                    <table class="table table-sm table-striped dragdrop_form" id="mod_news_article_list">
                        <thead class="thead-dark">
                            <tr>
                                <th></th>
                                <th></th>
                                <th><?php echo self::t('Title') ?></th>
                                <th><?php echo self::t('Group') ?></th>
                                <th><?php echo self::t('Active') ?></th>
                                <th><?php echo self::t('Tags') ?></th>
                                <th><?php echo self::t('Images') ?></th>
                                <th><?php echo self::t('Starting date') ?></th>
                                <th><?php echo self::t('Expiry date') ?></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th><input type="checkbox" name="manage_articles_all" id="<?php echo $sectionID; ?>_all" value="all" onchange='javascript: var boxes = document.forms["modify_<?php echo $sectionID; ?>"].elements[ "manage_articles[]" ]; for (var i=0, len=boxes.length; i<len; i++) { boxes[i].checked = this.checked;}' /></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
<?php foreach($data['articles'] as $article): ?>
                            <tr id="article_id:<?php echo $article['article_id']; ?>">
                                <td<?php if ($settings['view_order'] == 0): echo ' class="dragdrop_item"'; endif; ?>><i class="fa fas fa-fw fa-arrows-alt-v"></i></td>
                                <td>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>" title="<?php echo self::t('Modify') ?>">
                                        <span class="fa fa-fw fa-edit"></span>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>">
                                        <span title="Article ID <?php echo $article['article_id'] ?>"><?php echo $article['title']; ?></span>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $data['edit_url'] ?>section_id=<?php echo $sectionID; ?>&amp;group_id=<?php echo $article['group_id']; ?>&amp;tab=g" title="<?php echo self::t('Modify') ?>">
                                        <?php echo $article['group_title'] ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript: confirm_link('<?php echo self::t('Are you sure?') ?>', '<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;active=<?php echo $article['active']!=0 ? '0':'1'; ?>');" title="<?php if ($article['active'] == 1): echo self::t('Deactivate article'); else: echo self::t('Activate article'); endif;?>">
<?php if ($article['active'] == 1): ?>
                                    <span class="fa fa-fw fa-check"></span>
<?php else: ?>
                                    <span class="fa fa-fw fa-eye-slash"></span>
<?php endif; ?></a>
                                </td>
                                <td>
                                    <?php echo $article['tags'] ?>
                                </td>
                                <td>
                                    <?php echo count($article['images']) ?>
                                </td>
                                <td>
                                    <?php echo ($article['published_when']>0 ? \CAT\Addon\cmsbridge::formatDate($article['published_when']) : '') ?>
                                </td>
                                <td>
                                    <?php echo ($article['published_until']>0 ? \CAT\Addon\cmsbridge::formatDate($article['published_until']) : '') ?>
                                </td>
                                <td>
<?php if ($article['is_visible'] == true): ?>
                                    <span class="fa fa-fw fa-calendar-check" title="<?php echo self::t('Article is visible') ?>"></span>
<?php else: ?>
                                    <span class="fa fa-fw fa-calendar-times" title="<?php echo self::t('Article is NOT visible') ?>"></span>
<?php endif; ?></a>

                                </td>
                                <td>
<?php if (($article['position'] != 1) && ($settings['view_order'] == 0)): ?>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;move=up" title="<?php echo self::t('Move up') ?>">
                                        <span class="fa fa-fw fa-arrow-circle-up mod_journal_arrow"></span>
                                    </a>
<?php else: ?>
                                    <span class="fa fa-fw fa-arrow-circle-up nwi-disabled mod_journal_arrow"></span>
<?php endif; ?>
                                </td>
                                <td>
<?php  if (($article['position'] != $data['num_articles']) && ($settings['view_order'] == 0)): ?>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;move=down" title="<?php echo self::t('Move down') ?>">
                                        <span class="fa fa-fw fa-arrow-circle-down mod_journal_arrow"></span>
                                    </a>
<?php else: ?>
                                    <span class="fa fa-fw fa-arrow-circle-down nwi-disabled mod_journal_arrow"></span>
<?php endif; ?>
                                </td>
                                <td>
                                    <input type="checkbox" name="manage_articles[]" value="<?php echo $article['article_id'] ?>" onchange='javascript: document.getElementById("<?php echo $sectionID ?>_all").checked &= this.checked' />
                                </td>
                                <td>
                                    <a href="javascript: confirm_link('<?php echo self::t('Are you sure?') ?>', '<?php echo CMSBRIDGE_CMS_URL; ?>/modules/journal/delete_article.php?page_id=<?php echo $pageID; ?>&amp;section_id=<?php echo $sectionID; ?>&amp;article_id=<?php echo $article['article_id']; ?>');" title="<?php echo self::t('Delete') ?>">
                                        <span class="fa fa-fw fa-trash nwi-delete"></span>
                                    </a>
                                </td>
                                <td<?php if ($settings['view_order'] == 0): ?> class="dragdrop_item"<?php endif; ?>>&nbsp;</td>
                            </tr>
<?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <table class="table table-sm">
                    <tr>
                        <td class="btnline">

                        </td>
                        <td style="text-align:right" class="btnline">
                            <div class="mod_news_article_tools"><?php echo self::t('Action') ?>:
                                <select name="action">
                                    <option value="" selected="selected"></option>
                                    <option value="copy"><?php echo self::t('Copy') ?></option>
                                    <option value="copy_with_tags"><?php echo self::t('Copy with tags') ?></option>
                                    <option value="move"><?php echo self::t('Move') ?></option>
                                    <option value="move_with_tags"><?php echo self::t('Move with tags') ?></option>
                                    <option value="delete"><?php echo self::t('Delete') ?></option>
                                    <option value="activate"><?php echo self::t('Activate') ?></option>
                                    <option value="deactivate"><?php echo self::t('Deactivate') ?></option>
                                    <option value="tags"><?php echo self::t('Assign tags') ?></option>
                                    <option value="group"><?php echo self::t('Assign group') ?></option>
                                </select>
                                <input name="continue" type="submit" onclick="return checkActionAndArticles()" value="<?php echo self::t('Continue') ?>" />
                             </div>
                        </td>
                    </tr>
                </table>
<?php else: echo $add_article_button; endif; ?>
            </form>

            <script type="text/javascript">
                var LOAD_DRAGDROP = true;
                var ICONS = '<?php echo CMSBRIDGE_CMS_URL."/modules/journal/images" ?>';
            </script>

<?php if (count($data['importable_sections'])>0): ?>
            <h2><?php echo self::t('Import section') ?></h2>
            <form name="importsection" id="import_<?php echo $sectionID; ?>" action="<?php echo $data['edit_url'] ?>" method="post" enctype="multipart/form-data">
                <?php echo \CAT\Addon\cmsbridge::admin()->getFTAN(); ?>
                <input type="hidden" name="section_id" value="<?php echo $sectionID; ?>" />
                <input type="hidden" name="page_id" value="<?php echo $pageID; ?>" />
                <input type="hidden" name="import" value="1" />
                <table class="table table-sm">
                <tr>
                    <td class="setting_name"><?php echo self::t('Section') ?>:</td>
                    <td class="setting_value">
                        <select name="source_id" id="source_id_<?php echo $sectionID; ?>">
<?php foreach($data['importable_sections'] as $module => $sections): ?>
                            <option disabled value="0">[--- <?php echo self::t('Module').': '.$module ?> ---]</option>
<?php foreach($sections as $id => $name): ?>
                            <option data-module="<?php echo $module ?>" value="<?php echo $id ?>"><?php echo self::t('Section').' #'.$name ?></option>
<?php endforeach; endforeach; ?>
                        </select>
                    </td>
                </tr>
<?php if(!count($data['articles'])>0): ?>
                <tr>
                    <td class="setting_name"><?php echo self::t('Include settings') ?>:</td>
                    <td class="setting_value">
                        <input type="checkbox" name="include_settings" />
                    </td>
                </tr>
<?php endif; ?>
                <tr class="importgroups">
                    <td class="setting_name"><?php echo self::t('Include groups') ?>:</td>
                    <td class="setting_value">
                        <input type="checkbox" name="include_groups" />
                    </td>
                </tr>
                <tr class="importtags">
                    <td class="setting_name"><?php echo self::t('Include tags') ?>:</td>
                    <td class="setting_value">
                        <input type="checkbox" name="include_tags" />
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        <input name="save" type="submit" value="<?php echo self::t('Import') ?>" />
                    </td>
                    <td>
                    </td>
                </tr>
                </table>
            </form>
<?php endif; ?>
        </div>