        <noscript>
            <!-- Formular -->
            <div id="fotos"><h3><?php echo self::t('Image upload')?></h3>
                  <input type="file" name="foto[]" accept="image/*" />  <br />
                  <input type="file" name="foto[]" accept="image/*" />  <br />
                  <input type="file" name="foto[]" accept="image/*" />  <br />
                  <input type="file" name="foto[]" accept="image/*" />   <br />
                  <input type="file" name="foto[]" accept="image/*" />   <br />
                  <input type="file" name="foto[]" accept="image/*" />   <br />
            </div>
        </noscript>

        <main role="main" class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <!-- Our markup, the important part here! -->
                    <div id="drag-and-drop-zone" class="dm-uploader p-5">
                        <div class="mb-5 mt-5 text-muted"><?php echo self::t('Drag &#38; drop here'); ?></div>
                        <div class="btn btn-primary btn-block mb-5">
                            <input type="file" title=<?php echo "'".self::t('Click to add')."'"; ?> />
                        </div>
                    </div><!-- /uploader -->
                </div>
                <div class="col-md-6 col-sm-12">
                    <div class="card h-100">
                        <ul class="list-unstyled p-2 d-flex flex-column col" id="files">
                            <li class="text-muted text-center empty"><?php echo self::t('No files uploaded yet.'); ?></li>
                        </ul>
                    </div>
                </div>
            </div><!-- /file list -->

            <div class="row">
                <div class="col-12">
                    <div class="card h-100">
                        <ul class="list-group list-group-flush" id="status"></ul>
                    </div>
                </div>
            </div> <!-- /status messages -->

        </main> <!-- /container -->

        <table class="table table-sm">
        <tr>
        	<td>
        		<input name="save" type="submit" value="<?php echo self::t('Save'); ?>" />
        		<input name="saveandback" type="submit" value="<?php echo self::t('Save and go back'); ?>" />
        	</td>
        	<td style="text-align:right">
        		<input name="cancel" type="submit" value="<?php echo self::t('Cancel') ?>" class="btn btn-secondary" />
        	</td>
        </tr>
        </table>
    </form>

<script type="text/javascript">
    var JOURNAL_UPLOAD_URL = "<?php echo CMSBRIDGE_CMS_URL."/modules/".JOURNAL_MODDIR."/uploader/upload.php?section_id=".$sectionID."&article_id=".$data['article_id']; ?>";
    var JOURNAL_COMPLETE_MESSAGE = "<?php echo self::t('Complete'); ?>";
    var JOURNAL_SIZE_MESSAGE = "<?php echo self::t('The file size exceeds the limit'); ?>";
    var JOURNAL_IMAGE_MAX_SIZE = "<?php echo $settings['imgmaxsize']; ?>";

    jQuery.noConflict();
    (function($) {
        "use strict";
        $.get(CMS_URL+"/modules/<?php echo JOURNAL_MODDIR ?>/js/jquery.furl.js", function( data ) {
            $('#title<?php echo $pageID ?>').furl({id:'link<?php echo $pageID ?>', seperate: '<?php echo PAGE_SPACER ?>' });
        });
        $.get(CMS_URL+"/modules/<?php echo JOURNAL_MODDIR ?>/uploader/js/jquery.dm-uploader.js", function( data ) {
            $.get(CMS_URL+"/modules/<?php echo JOURNAL_MODDIR ?>/uploader/ui.js", function( data ) {
                $.get(CMS_URL+"/modules/<?php echo JOURNAL_MODDIR ?>/uploader/config.js");
            });
        });
    })(jQuery);
</script>

    <!-- File item template -->
    <script type="text/html" id="files-template">
        <li class="media">
            <img class="mr-3 mb-2 preview-img" src="<?php echo CMSBRIDGE_CMS_URL."/modules/".JOURNAL_MODDIR."/images/nopic.png" ?>" alt="Generic placeholder image">
            <div class="media-body mb-1">
                <p class="mb-2">
                    <strong>%%filename%%</strong> - Status: <span class="text-muted">Waiting</span>
                </p>
                <div class="progress mb-2">
                    <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
                         role="progressbar"
                         style="width: 0%"
                         aria-valuenow="0"
                         aria-valuemin="0"
                         aria-valuemax="100">
                    </div>
                </div>
                <hr class="mt-1 mb-1" />
            </div>
        </li>
    </script>

    <!-- Status item template -->
    <script type="text/html" id="status-template">
        <li class="list-group-item"><strong>%%message%%</strong></li>
    </script>