<div id="mod_journal_uploader"></div>

<div id="console" class="mod_journal_console"></div>

<script type="text/javascript">
//<![CDATA[
    (function($) {
        /* uploader */
        $.get(CMS_URL+"/modules/journal/js/plupload.full.min.js", function() {
            $("head").append('<link rel="stylesheet" type="text/css" href="'+CMS_URL+'/modules/journal/js/jquery.plupload.queue/css/jquery.plupload.queue.css" media="all">');
            $.get(CMS_URL+"/modules/journal/js/jquery.plupload.queue/jquery.plupload.queue.min.js", function() {
                $.get(CMS_URL+"/modules/journal/js/jquery.ui.plupload/jquery.ui.plupload.js", function() {
                    $.get(CMS_URL+"/modules/journal/js/i18n/<?php echo strtolower(LANGUAGE) ?>.js", function() {
                        var upl = $("#mod_journal_uploader").pluploadQueue({
                            runtimes : "html5,html4",
                            url : CMS_URL+"/modules/journal/uploader/upload.php",
                            chunk_size : '1mb',
                            unique_names : false,
                            multiple_queues : true,
                            dragdrop: true,
                            multipart_params: { "article_id": "<?php echo $data['article_id']; ?>" },
                            filters : {
                                max_file_size : "<?php echo (empty($settings['imgmaxsize']) ? 0 : $settings['imgmaxsize']); ?>",
                                mime_types: [
                                    {title : "Image files", extensions : "<?php echo implode(',',self::getAllowedSuffixes()) ?>"},
                                ]
                            },
                            // Resize images on clientside if we can
                            resize: {
                                width : <?php echo (empty($settings['imgmaxwidth']) ? 4096 : $settings['imgmaxwidth']); ?>,
                                height : <?php echo (empty($settings['imgmaxheight']) ? 4096 : $settings['imgmaxheight']); ?>,
                                quality : 100,
                                crop: <?php echo ((isset($settings['crop']) && $settings['crop']=='Y') ? 'true' : 'false'); ?>
                            },
                            init: {
                                FileUploaded: function(uploader, file, response) {
                                    var result = JSON.parse(response.response);
                                    if(result.status == "error") {
                                        file.status = plupload.FAILED;
                                        document.getElementById('console').innerHTML += "\nError: "+result.message;
                                    }
                                }
// TODO: Nach dem Abarbeiten der Queue die Seite neu laden, damit die neuen Bilder in der Liste auftauchen
                            }
                        });
                    }); // get lang file
                });     // get jquery.ui.plupload.js
            });         // get jquery.plupload.queue.min.js
        });             // get plupload.full.min.js
    })(jQuery);
//]]>
</script>