<nav>
        <ul>
            <li class="licol1<?php if($data['curr_tab']=='p'): ?> active<?php endif; ?>">
                <a href="<?php echo $data['edit_url']; ?>tab=p"><i class="fa fa-fw fa-clone"></i> <span><?php echo self::t('Articles') ?></span></a>
            </li>
            <li class="licol2<?php if($data['curr_tab']=='g'): ?> active<?php endif; ?>">
                <a href="<?php echo $data['edit_url']; ?>tab=g"><i class="fa fa-fw fa-cubes"></i> <span><?php echo self::t('Groups') ?></span></a>
            </li>
<?php if($settings['mode']=='advanced'): ?>
            <li class="licol3<?php if($data['curr_tab']=='s'): ?> active<?php endif; ?>">
                <a href="<?php echo $data['edit_url']; ?>tab=s"><i class="fa fa-fw fa-tags"></i> <span><?php echo self::t('Tags') ?></span></a>
            </li>
<?php endif; ?>
            <li class="licol4<?php if($data['curr_tab']=='o'): ?> active<?php endif; ?>">
                <a href="<?php echo $data['edit_url']; ?>tab=o"><i class="fa fa-fw fa-wrench"></i> <span><?php echo self::t('Options') ?></span></a>
            </li>
            <li class="red<?php if($data['curr_tab']=='r'): ?> active<?php endif; ?>">
                <a href="<?php echo $data['edit_url']; ?>tab=r"><i class="fa fa-fw fa-info-circle"></i> <span><?php echo self::t('Readme') ?></span></a>
            </li>
        </ul>
</nav><br style="clear:left" />