<?php include 'backend_header.phtml'; ?>
    <div class="tabs">
<?php
    include 'modify_tabs.phtml';
    include 'modify_tab_posts.phtml';       // content of postings tab
    include 'modify_tab_groups.phtml';      // content of groups tab
    include 'modify_tab_tags.phtml';        // content of tags tab
    include 'modify_tab_settings.phtml';    // content of tags tab
    include 'modify_tab_readme.phtml';      // content of readme tab
?>
    </div>
</div>