<?php
    $add_article_button = '<input type="submit" class="btn btn-primary" name="mod_journal_add_article" value="' . self::t('Add article') . '" />';
?>
        <div id="main-tab-content1" class="main-tab-content">
<?php if(count($data['articles'])>0): if(count($data['articles'])>20): echo $add_article_button; endif; ?>
            <div style="text-align:right;font-style:italic">
                <?php echo self::t('Order by'), ": <span class=\"\" title=\"", ( $settings['view_order']=='0' ? self::t('The setting &quot;custom&quot; allows the manual sorting of articles via up/down arrows.') : '') ,"\">", $data['lang_map'][$settings['view_order']] ?></span>
            </div>
<?php endif; ?>
            <form name="modify_<?php echo $sectionID; ?>" action="<?php echo $data['edit_url'] ?>" method="post" enctype="multipart/form-data">
                <?php echo self::admin()->getFTAN(); ?>
                <input type="hidden" name="section_id" value="<?php echo $sectionID; ?>" />
                <input type="hidden" name="page_id" value="<?php echo $pageID; ?>" />
<?php if(count($data['articles'])>0): ?>
                <div class="scrollable">
                    <table class="table table-sm table-striped dragdrop_form" id="mod_news_article_list">
                        <thead class="thead-dark">
                            <tr>
                                <th></th>
                                <th></th>
                                <th><?php echo self::t('Title') ?></th>
                                <th><?php echo self::t('Group') ?></th>
                                <th><?php echo self::t('Active') ?></th>
                                <th><?php echo self::t('Tags') ?></th>
                                <th><?php echo self::t('Starting date') ?></th>
                                <th><?php echo self::t('Expiry date') ?></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th><input type="checkbox" name="manage_articles_all" id="<?php echo $sectionID; ?>_all" value="all" onchange='javascript: var boxes = document.forms["modify_<?php echo $sectionID; ?>"].elements[ "manage_articles[]" ]; for (var i=0, len=boxes.length; i<len; i++) { boxes[i].checked = this.checked;}' /></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
<?php foreach($data['articles'] as $article): ?>
                            <tr id="article_id:<?php echo $article['article_id']; ?>">
                                <td<?php if ($settings['view_order'] == 0): echo ' class="dragdrop_item"'; endif; ?>>&nbsp;</td>
                                <td>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>" title="<?php echo self::t('Modify') ?>">
                                        <span class="fa fa-fw fa-edit"></span>
                                    </a>
                                </td>
                                <td>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>">
                                        <span title="Article ID <?php echo $article['article_id'] ?>"><?php echo $article['title']; ?></span>
                                    </a>
                                </td>
                                <td>
                                    <?php echo $article['group_title'] ?>
                                </td>
                                <td>
                                    <a href="javascript: confirm_link('<?php echo self::t('Are you sure?') ?>', '<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;active=<?php echo $article['active']!=0 ? '0':'1'; ?>');" title="<?php if ($article['active'] == 1): echo self::t('Deactivate article'); else: echo self::t('Activate article'); endif;?>">
<?php if ($article['active'] == 1): ?>
                                    <span class="fa fa-fw fa-eye"></span>
<?php else: ?>
                                    <span class="fa fa-fw fa-eye-slash"></span>
<?php endif; ?></a>
                                </td>
                                <td>
                                    <?php echo $article['tags'] ?>
                                </td>
                                <td>
                                    <?php echo $article['publishing_date'] ?>
                                </td>
                                <td>
                                    <?php echo $article['publishing_end_date'] ?>
                                </td>
                                <td>
                                    <?php echo $article['icon']; ?>
                                </td>
                                <td>
<?php if (($article['position'] != 1) && ($settings['view_order'] == 0)): ?>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;move=up" title="<?php echo self::t('Move up') ?>">
                                        <span class="fa fa-fw fa-arrow-circle-up mod_journal_arrow"></span>
                                    </a>
<?php else: ?>
                                    <span class="fa fa-fw fa-arrow-circle-up nwi-disabled mod_journal_arrow"></span>
<?php endif; ?>
                                </td>
                                <td>
<?php  if (($article['position'] != $data['num_articles'])&&($settings['view_order'] == 0)): ?>
                                    <a href="<?php echo $data['edit_url'] ?>article_id=<?php echo $article['article_id']; ?>&amp;move=down" title="<?php echo self::t('Move down') ?>">
                                        <span class="fa fa-fw fa-arrow-circle-down mod_journal_arrow"></span>
                                    </a>
<?php else: ?>
                                    <span class="fa fa-fw fa-arrow-circle-down nwi-disabled mod_journal_arrow"></span>
<?php endif; ?>
                                </td>
                                <td>
                                    <input type="checkbox" name="manage_articles[]" value="<?php echo $article['article_id'] ?>" onchange='javascript: document.getElementById("<?php echo $sectionID ?>_all").checked &= this.checked' />
                                </td>
                                <td>
                                    <a href="javascript: confirm_link('<?php echo self::t('Are you sure?') ?>', '<?php echo CMSBRIDGE_CMS_URL; ?>/modules/journal/delete_article.php?page_id=<?php echo $pageID; ?>&amp;section_id=<?php echo $sectionID; ?>&amp;article_id=<?php echo $article['article_id']; ?>');" title="<?php echo self::t('Delete') ?>">
                                        <span class="fa fa-fw fa-close nwi-delete"></span>
                                    </a>
                                </td>
                                <td<?php if ($settings['view_order'] == 0): ?> class="dragdrop_item"<?php endif; ?>>&nbsp;</td>
                            </tr>
<?php endforeach; ?>

                        </tbody>
                    </table>
                </div>

                <table class="table table-sm">
                    <tr style="background-color:transparent">
                        <td>
<?php echo $add_article_button ?>
                        </td>
                        <td style="text-align:right">
                            <div class="mod_news_article_tools"><?php echo self::t('Action') ?>:
                                <select name="action">
                                    <option value="" selected="selected"></option>
                                    <option value="copy"><?php echo self::t('Copy') ?></option>
                                    <option value="copy_with_tags"><?php echo self::t('Copy with tags') ?></option>
                                    <option value="move"><?php echo self::t('Move') ?></option>
                                    <option value="move_with_tags"><?php echo self::t('Move with tags') ?></option>
                                    <option value="delete"><?php echo self::t('Delete') ?></option>
                                    <option value="activate"><?php echo self::t('Activate') ?></option>
                                    <option value="deactivate"><?php echo self::t('Deactivate') ?></option>
                                    <option value="tags"><?php echo self::t('Assign tags') ?></option>
                                    <option value="group"><?php echo self::t('Assign group') ?></option>
                                </select>
                                <input name="continue" type="submit" onclick="return checkActionAndArticles()" value="<?php echo self::t('Continue') ?>" />
                             </div>
                        </td>
                    </tr>
                </table>
<?php else: echo $add_article_button; endif; ?>
            </form>

            <script type="text/javascript">
                var LOAD_DRAGDROP = true;
                var ICONS = '<?php echo CMSBRIDGE_CMS_URL."/modules/journal/images" ?>';
            </script>

<?php if ($data['importable_sections']>0): ?>
            <h2><?php echo self::t('Import section') ?></h2>
            <form name="import" action="<?php echo CMSBRIDGE_CMS_URL; ?>/modules/journal/import.php" method="post" enctype="multipart/form-data">
                <?php echo \CAT\Addon\junction::admin()->getFTAN(); ?>
                <input type="hidden" name="section_id" value="<?php echo $sectionID; ?>" />
                <input type="hidden" name="page_id" value="<?php echo $pageID; ?>" />
                <table class="table table-sm">
                <tr>
                    <td class="setting_name"><?php echo self::t('Import') ?>:</td>
                    <td class="setting_value">
                        <select name="source_id">
<?php if(isset($nwi_sections) && is_array($nwi_sections) && count($nwi_sections)>0): ?>
                            <option disabled value="0">[--- News with Images ---]</option>
<?php foreach($nwi_sections as $source): if($source['section_id'] != $sectionID): ?>
                            <option value="<?php echo $source['section_id'] ?>"><?php echo self::t('Section').' '.$source['section_id'] ?></option>
<?php endif; endforeach; ?>
<?php endif; if(isset($news_sections) && is_array($news_sections) && count($news_sections)>0): ?>
                            <option disabled value="0">[--- (classical) News ---]</option>
                            <?php foreach($news_sections as $source): ?>
                            <option value="<?php echo $source['section_id'] ?>"><?php echo self::t('Section').' '.$source['section_id'] ?></option>
                            <?php endforeach; ?>
<?php endif; if(isset($topics_sections) && is_array($topics_sections) && count($topics_sections)>0): foreach($topics_sections as $name => $topics ): if(count($topics)>0): ?>
                            <option disabled value="0">[--- <?php echo $name ?> ---]</option>
<?php foreach($topics as $source): ?>
                            <option value="<?php echo $source['section_id'] ?>"><?php echo self::t('Section').' '.$source['section_id'] ?></option>
<?php endforeach; endif; endforeach; endif; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        <input name="save" type="submit" value="<?php echo self::t('Save') ?>" />
                    </td>
                    <td>
                    </td>
                </tr>
                </table>
            </form>
<?php endif; ?>
        </div>